nohup: ignoring input
Running simulation number: 2
------------------------------------------------------------------
Activating conda environment: vertex_model

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.


Running simulations for parameter: push_out_force_strength
Running simulation with push_out_force_strength = 2.0
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
Simulation Parameters: simulation_2
dt: 0.05
time_limit: 100
save_frame_interval: 10
Done.
Final window area: 119.59071659217237
Max velocity at t=10: 0.9718113115276701
Running simulation with push_out_force_strength = 2.1
/home/gili/anaconda3/envs/vertex_model/lib/python3.11/site-packages/numpy/_core/getlimits.py:551: UserWarning: Signature b'\x00\xd0\xcc\xcc\xcc\xcc\xcc\xcc\xfb\xbf\x00\x00\x00\x00\x00\x00' for <class 'numpy.longdouble'> does not match any known type: falling back to type probe function.
This warnings indicates broken support for the dtype!
  machar = _get_machar(dtype)
